server:
  port: 7002


eureka:
  instance:
    hostname: eurekaserver2   #eureka服务端的实例名称
  client:
    register-with-eureka: false   #false表示不向注册中心注册自己
    fetch-registry: false   #false表示自己端就是注册中心
    service-url:
      defaultZone: http://eurekaserver1:7001/eureka/
  server:
    # 关闭自我保护机制，保证不可用服务被及时剔除
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000
spring:
  application:
    name: cloud-eureka-service